QtiGralloc: Remove an unused variable
hardware/qcom-caf/msm8998/display/display-commonsys-intf/gralloc/QtiGralloc.cpp:188:14: error: unused variable 'p' [-Werror,-Wunused-variable]
  qti_ycbcr *p = reinterpret_cast<qti_ycbcr *>(in.data());
             ^

Signed-off-by: khirendra03 <khirendrapatel3@gmail.com>